@startuml DiagramaComponentes

package "API Node.js (Express)" {

  [Rotas de Usuários] --> [Controller de Usuários]
  [Controller de Usuários] --> [Service de Usuários]
  [Service de Usuários] --> [Model Usuario]

  [Rotas de Serviços] --> [Controller de Serviços]
  [Controller de Serviços] --> [Service de Serviços]
  [Service de Serviços] --> [Model Serviço]

  [Rotas Admin] --> [Controller Admin]
  [Controller Admin] --> [Service Admin]
  [Service Admin] --> [Model Usuario]
  [Service Admin] --> [Model Serviço]

  [Auth Middleware] --> [Service de Autenticação]
  [Service de Autenticação] --> [Model Usuario]
}

@enduml
